export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const GET_SUBTRANSACTION_BY_TRANSACTION = "GET_SUBTRANSACTION_BY_TRANSACTION";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";